### ISSUE TITLE
Передаваемые environments

### ISSUE THREAD

**Issue by VD42** [All-Cups/highloadcup#14]
Сейчас в условиях задачи указаны следующие передаваемые environments:

ADDRESS: default
Port: 8000;
Schema: http

Но есть подозрение, что Port и Schema не передаются. Просьба это проверить, а также уточнить формат данных, т.к. "8000;" выглядит ошибкой.

**Comment by mastersobg** [comment]
I confirm it. I printed env variables and there're no port and schema among them.

**Comment by SannikovDmitry** [comment]
Убрали это
