### ISSUE TITLE
Ошибка! Error in the launch system

### ISSUE THREAD

**Issue by lightkeeper217** [All-Cups/highloadcup#15]
Требуется подробное описание ошибки. 
Docker-образ локально работает, в связи с чем не понятно, что пошло не так.
Если какая-то проблема на серверах, то вопрос следующий: будет ли считаться данная попытка потраченной из 10 в день?
Можно ли как-то запустить отправленное решение повторно? (если по новой отправлять образ, то он не воспринимается, т.к. идентичен предыдущему, но менять в программе по сути не чего, т.к. не известно, как она себя ведёт на сервере. 
Возможен ли автоматический запуск системы через некоторое время, если известно, что проблема была не в отправленном решении?

**Comment by SannikovDmitry** [comment]
Сейчас лимитов нет. Перезапуски добавим до 12 марта.
