### ISSUE TITLE
Explore request: Code = 503, Message = service unavailable

### ISSUE THREAD

**Issue by Hartigan** [All-Cups/highloadcup#16]
Так как сервер после этого ответа не подымается, предлагаю заканчивать решение досрочно, чтобы освобождать машину и возвращать результат решения раньше.

**Comment by snupy** [comment]
Я так понимаю вы пытаетесь сделать explore на большую площадь...

**Comment by artem-leonov** [comment]
Я пытаюсь на большую сделать, да. Но вроде ограничений на запрос нет, печально, что он падает. Придется эвристически подбирать

**Comment by Hartigan** [comment]
Суть не в том, что падает, а чтобы попытка раньше сворачивалась, так как нет смысла дальше пинговать упавший сервер.

**Comment by artem-leonov** [comment]
А я бы предложил рестартовать сервис, например. А еще лучше не падать, но это уж я замечтался

**Comment by SannikovDmitry** [comment]
Это механика игры. Изучайте
