### ISSUE TITLE
Алгоритм команды Dig / Dig command algorithm

### ISSUE THREAD

**Issue by lightkeeper217** [All-Cups/highloadcup#17]
С учётом того, что поле может раскапываться только по одной клетке в глубину, то предлагаю следующие варианты использования команды Dig:
1. Передача точки копания без глубины, т.к. сервер всё равно знает, на какой глубине были раскопки.
2. Использование глубины копания для передачи количества уровней, на которые нужно прокопать (от текущих раскопок). Соответственно один уровень копания тратит лицензию.  Таким образом при передачи новой лицензии одной командой пользователь может прокопать до 3х уровней (бесплатная лицензия) /до 5ти уровней (платная лицензия).
----
Considering that the field can only be dug one cell deep, I suggest the following options for using the Dig command:
1. Transfer of the digging point without depth, because the server still knows at what depth the excavations were.
2. Using the depth of digging to convey the number of levels to be dug (from the current excavation). Accordingly, one level of digging wastes a license. Thus, when transferring a new license with one command, the user can dig up to 3 levels (free license) / up to 5 levels (paid license).

**Comment by lightkeeper217** [comment]
Хотя смысл в текущем положении тоже есть: чтобы многопотчники следили, чтоб команда Dig с более глубоким копанием из одного потока не опередила команду с низким уровнем копания из другого потока.

**Comment by dbf256** [comment]
Глубину уж точно можно сейчас убрать т.к. нет смысла ее передавать.

**Comment by SannikovDmitry** [comment]
Механику игры менять не будем.
