### ISSUE TITLE
`/[0-9]m/` silently dropped from logs

### ISSUE THREAD

**Issue by alex3d** [All-Cups/highloadcup#18]
`/[0-9]m/` regex matches silently dropped from logs.

`print("TEST: duration=123ms '1m' 'am' '123MS' ")` becomes `TEST: duration=12s '' 'am' '123MS'` in logs.

Looks like failed attempt to remove ANSI escape sequences.

**Comment by SannikovDmitry** [comment]
Will be fixed

**Comment by kuviman** [comment]
Same for symbol `^`

**Comment by xammi** [comment]
Before fix:
```
r'\u001B\[((\d+\;)*\d+[mAB]?\s*)?'
r'(\d|\;)m'
```
Now:
```
r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])'
r'\x1B\(\w'
```
