### ISSUE TITLE
Алгоритм команды explore / расположение кладов.

### ISSUE THREAD

**Issue by lightkeeper217** [All-Cups/highloadcup#19]
Выдержка из правил: "Чем глубже раскопки, тем больше нужно времени на один вызов API.  При этом есть шанс, что количество золота в кладе будет больше. При этом максимальная глубина не гарантирует большую стоимость сокровища по сравнению с другими этажами." Вроде как идея выглядит красиво - копай вглубь, и находи золото, но при текущей реализации команда explore выдаёт количество закопанных кладов и сами клады располагаются один на клетке. Что сводит весь алгоритм копания к тому, что если explore сказала, что клад есть, то копай пока до него не доберешься.
На мой взгляд, было бы интереснее если кладов было бы несколько в одной клетке, например, по количеству монет на этажах: 0, 0, 4, 7, 0, 10, 6, 15, 0, 0, при этом explore говорила бы о наличии клада в ячейке (в первоначальном варианте). Тогда участникам после каждой раскопки предстояло бы решать задачу - стоит ли копать дальше?

**Comment by SannikovDmitry** [comment]
Это механика игры. Менять не будем. Изучайте.
