### ISSUE TITLE
На что конкретно влияет SEED?

### ISSUE THREAD

**Issue by artemik** [All-Cups/highloadcup#20]
Из спецификации: 

> При генерации мира используется параметр SEED. Он определяет сколько кладов и на каком этаже будет сгенерировано, какая будет ценность каждого клада и какой этаж будет оптимальным по соотношению ценности кладов к стоимости их добычи.

Вопросы: 
1. Влияет ли SEED на поведение/длительность API сервера? Можно ли полагаться, что они будут такими же на финальных SEED какие они сейчас?
2. Влияет ли SEED на цену и закономерность платных лицензий?

**Comment by SannikovDmitry** [comment]
Все было написано в описании задачи
