### ISSUE TITLE
Выводить первую строчку логов

### ISSUE THREAD

**Issue by mortido** [All-Cups/highloadcup#24]
В данный момент очень сложно различать решения между собой. Было бы реально круто выводить первую строчку из логов где-нибудь на самом решении. Например надо кнопкой "Посмотреть лог решения" переименовав его в "Посмотреть полный лог решения"

Как это можно использовать участникам удобно (пример).
В `Dockerfile` добавить:
```
ARG HELLO_MSG=""
ENV HELLO_MSG=$HELLO_MSG
```

В `main.cpp`:
```
int main(int argc, char **argv) {
  const char *hello_msg = std::getenv("HELLO_MSG");
  if (hello_msg) {
    mortido::log() << hello_msg << std::endl;
  }
```

в `Makefile`:
```
IMAGE=dima_molodec
RELEASE_TAG=stor.highloadcup.ru/rally/diggy_diggy_hole

build:
	docker build -t $(IMAGE) . --build-arg HELLO_MSG='$(msg)'

push:	build
	docker tag $(IMAGE):latest $(RELEASE_TAG)
	docker push $(RELEASE_TAG)
```

После чего для отправки "помеченных" версий можно будет вызывать `make push msg="Hello, Dima!"`

**Comment by SannikovDmitry** [comment]
Сделаем такое в следующем релизе.
