### ISSUE TITLE
Рейтинговый SEED не содержит гарантированных 23 030 000 монет

### ISSUE THREAD

**Issue by artemik** [All-Cups/highloadcup#26]
Набор моих рейтинговых запусков и анализ всего поля полностью говорят о том, что поле содержит 490 000 кладов (как и обещано), но лишь 12 280 652 монет из обещанных 23 030 000! Такое же поведение наблюдается и на некоторых пользовательских SEED, но похоже не на всех.

Мое решение абсолютно "тупое", копающее медленно, но абсолютно всё и вся и бесплатно - я сделал кучу запусков для полной проверки всего поля, чтобы подтвердить свои подозрения.

1. Прошу прокоментировать организаторов этот баг.
2. В текущем раунде, запускаются ли решения всех участников на одном и том же SEED для всех? Или для каждого он свой, но неизменный на протяжении рейтингового раунда? Судя по очкам участников, есть подозрение, что некоторых это не коснулось.

**Comment by SannikovDmitry** [comment]
Стоимость определяется в момент выкапывания. То, что обещано - это максимальное значение. Оно дается с запасом, предполагая максимальную стоимость каждого клада (а поскольку она случайная в каком-то интервале до максимальной, то по факту на поле кладов действительно на сумму меньшую, чем монет в банке - так и задумано.

Стоимость определяется в момент выкапывания и стоимость клада зависит от его глубины. Иными словами, если первые 5 кладов после начала игры выкопать на одинаковых глубинах (напр. 2,1,1,6,4) - то их стоимость при каждом запуске будет совпадать.

Иными словами, если клиент "тупой" и всегда ведёт себя одинаково - он будет получать одинаковую стоимость кладов. Расположение их так же совпадает. Поэтому создаётся впечатление, что вы точно определяете суммарную стоимость этих кладов. Но если выкопать те же клады в другой последовательности их глубин - их общая стоимость изменится.

**Comment by artemik** [comment]
Это прямо противоречит условиям задачи.

> SEED. Он определяет сколько кладов и на каком этаже будет сгенерировано, какая будет ценность каждого клада и какой этаж будет оптимальным по соотношению ценности кладов к стоимости их добычи.

Четко написано, что SEED определяет где будет лежать клад и сколько стоить. То есть набор (x, y, z, bonus).

Исходя из этого, также, не понимаю про последовательность. Есть клад ценностью 10 на 1-ом этаже в точке (1;1) и клад ценностью 20 на 5-ом этаже в точке (2;2), например. В какой бы последовательности они не выкапывались, сумма должна быть равна 30. Опять же, строго по условиям задачи.

**Comment by SannikovDmitry** [comment]
Не видим здесь противоречий.
