### ISSUE TITLE
Одинаковый SEED выдает разные поля!

### ISSUE THREAD

**Issue by artemik** [All-Cups/highloadcup#27]
>  **SEED**. Он определяет **сколько кладов** и на **каком этаже** будет сгенерировано, какая будет **ценность каждого клада** и какой этаж будет оптимальным по соотношению ценности кладов к стоимости их добычи.

Это условие не выполняется - используя только бесплатные лицензии, при одинаковых SEED и абсолютно одинаковых раскапываемых точках (полностью на 10 этажей), но раскапываемых в разном порядке, выдает разные ценности кладов, и, как результат, разный заработок в конце.

Любой может проверить.

**SEED: 2000**

#### 1 набор точек (X, Y, получаемая ценность) (порядок точек важен):
```
3001, 3042, 26
3004, 3033, 30
3003, 3027, 20
3000, 3020, 31
3004, 3019, 23
3000, 3013, 24
3000, 3012, 24
3003, 3010, 20
3002, 3004, 20
3002, 3003, 8
3001, 3001, 10
3004, 3000, 35
```
Итого: **271**.
#### 2 набор точек (X, Y, получаемая ценность) (порядок точек важен):
```
3004, 3000, 36
3000, 3020, 30
3004, 3033, 17
3004, 3019, 31
3000, 3013, 23
3001, 3042, 21
3003, 3027, 22
3000, 3012, 22
3002, 3003, 22
3003, 3010, 7
3001, 3001, 10
3002, 3004, 25
```
Итого: **266**.

Видно, что 266 != 271.

Совместно с https://github.com/All-Cups/highloadcup/issues/26 это срочный критический баг, прошу организаторов отреагировать. @SannikovDmitry

**Comment by artemik** [comment]
@SannikovDmitry @mr2dark ?

**Comment by SannikovDmitry** [comment]
Ответил в предыдущем треде
