### ISSUE TITLE
There are a lot of Cyrillic letters at the English version of the site

### ISSUE THREAD

**Issue by mr2dark** [All-Cups/highloadcup#5]
Particularly, in the contest category name and the contest description for the Gold Rush contest (PSA)

![Screenshot 2021-02-19 at 23 50 35](https://user-images.githubusercontent.com/3892442/108560836-6370b800-730e-11eb-8d94-870f31ec71b8.png)

**Comment by SannikovDmitry** [comment]
We will change it soon.
Thank you

**Comment by a-poptsov** [comment]
Please don't forget meta description(document.querySelector("head > meta:nth-child(12)")) that is used to generate preview link in different messengers .
![Screen Shot 2021-02-21 at 1 04 22 PM](https://user-images.githubusercontent.com/2743733/108620451-be58fb00-7445-11eb-9332-c197aba582b8.png)
![Screen Shot 2021-02-21 at 1 06 54 PM](https://user-images.githubusercontent.com/2743733/108620453-c0bb5500-7445-11eb-95b1-4c0758e14211.png)

**Comment by SannikovDmitry** [comment]
It will be released soon

Thank you
