### ISSUE TITLE
Wrong /explore bounds error message

### ISSUE THREAD

**Issue by rdbuf** [All-Cups/highloadcup#6]
Привет,
Если запросить /explore от Area(0, 0, 3600, 3600), то получим такое сообщение. По условию должно быть X: 0-3499. Должно быть, опечатка

422 "{"code":1000,"message":"wrong coordinates: X 0-3599 outside 0-3499"}

**Comment by powerman** [comment]
Нет, это не опечатка, оно означает "запрошенное значение 0-3599 вне разрешённого диапазона 0-3499". Может английский не очень удачно соответствует данной формулировке, конечно…

**Comment by rdbuf** [comment]
а, я в ночи не распарсил сообщение об ошибке - лучше бы связать текст с входными параметрами, например "sizeX=3600 is outside the allowed range", сейчас 3599 непонятно откуда берётся (плохая грамматика тоже не помогает)

**Comment by SannikovDmitry** [comment]
Улучшили вывод ошибки. Раскладка будет в среду.
```golang
"%w: X %d-%d is outside the allowed range 0-%d"
```
