### ISSUE TITLE
Explore -> 503 Service Unavailable

### ISSUE THREAD

**Issue by rdbuf** [All-Cups/highloadcup#7]
На запросы к /explore (0, 0, 2499, 2499) сервер кидается 503 Service Unavailable, см посылку sha256:296cb821838e66f88fa003287b016d76f302004f17277993ebb50383fd4c5e9f

Это не часть правил

**Comment by SannikovDmitry** [comment]
Часть игры. С вероятностью 1-2% любой запрос может вернуть `503 Service Unavailable`.

В бете не указывали некоторые факты, это сделано для баланса мира. Много будет указано в основном соревновании.

**Comment by rdbuf** [comment]
В моей посылке 100% запросов возвращают 503. Это странная механика

**Comment by SannikovDmitry** [comment]
@rdbuf 
```golang
ctx, log := fromRequest(params.HTTPRequest)
ctx, cancel := context.WithTimeout(ctx, srv.cfg.OpExploreAreaTimeout)
case ctx.Err() != nil:
		return errExploreArea(log, errServiceUnavailable, codeServiceUnavailable)
```

Timeout maybe :)

**Comment by rdbuf** [comment]
Ок, тогда какие лимиты на параметры?

**Comment by SannikovDmitry** [comment]
Это нюансы мира. Тестируйте.
