### ISSUE TITLE
Дополнение к правилам

### ISSUE THREAD

**Issue by dbf256** [All-Cups/highloadcup#9]
Хотелось бы видеть в правилах следующие моменты:
1) Как зависит длительность explore от площади
2) Как зависит длительность dig от глубины

**Comment by alex3d** [comment]
Это же легко самому посчитать. Вроде как правила осознанно недописали, чтобы мы реверсили поведение сервера.
// но я бы тоже не отказался от более подробных правил

**Comment by SannikovDmitry** [comment]
https://cups.mail.ru/ru/tasks/1057
